import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Shield, ArrowLeft, Lock, FileText, Scale, Info } from 'lucide-react';

const PageLayout = ({ title, icon: Icon, children }) => (
  <div className="min-h-screen bg-[#05060a] text-white selection:bg-primary/30 py-20 px-6">
    <div className="max-w-3xl mx-auto space-y-12">
      <Link to="/" className="inline-flex items-center gap-2 text-gray-500 hover:text-white transition-colors group">
        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
        Back to Home
      </Link>

      <div className="space-y-4">
        <div className="p-3 bg-primary/10 rounded-2xl w-fit border border-primary/20">
          <Icon className="text-primary w-8 h-8" />
        </div>
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight">{title}</h1>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="prose prose-invert prose-primary max-w-none space-y-8 text-gray-400 leading-relaxed"
      >
        {children}
      </motion.div>

      <div className="pt-12 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="flex items-center gap-3">
          <Shield className="text-primary w-5 h-5" />
          <span className="text-sm font-bold text-white">LegalAI Intelligence</span>
        </div>
        <p className="text-xs text-gray-600 uppercase tracking-widest font-bold">Last Updated: May 2026</p>
      </div>
    </div>
  </div>
);

export const PrivacyPolicy = () => (
  <PageLayout title="Privacy Policy" icon={Lock}>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">1. Data Collection</h2>
      <p>We collect minimal data necessary for document analysis. Your uploaded PDF files are processed securely using our AI pipeline and are automatically deleted after analysis unless you choose to save them to your profile.</p>
    </section>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">2. AI Processing</h2>
      <p>Documents are analyzed using industry-standard LLM providers (Groq, Gemini). We ensure that no personal identifying information is used to train these models.</p>
    </section>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">3. Security Measures</h2>
      <p>We employ end-to-end encryption for all document transmissions. Your data is stored in secure, encrypted databases with strict access controls.</p>
    </section>
  </PageLayout>
);

export const TermsOfService = () => (
  <PageLayout title="Terms of Service" icon={Scale}>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">1. Usage Agreement</h2>
      <p>By using LegalAI, you agree to provide authentic documents for analysis. Our service is designed to provide intelligence and simplification, not professional legal advice.</p>
    </section>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">2. User Responsibilities</h2>
      <p>Users are responsible for the content of the documents they upload. You must have the legal right to analyze any document you provide to our platform.</p>
    </section>
  </PageLayout>
);

export const AIDisclaimer = () => (
  <PageLayout title="AI Disclaimer" icon={Info}>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">Not Legal Advice</h2>
      <p>The analysis provided by LegalAI is generated by artificial intelligence. While we strive for 95%+ accuracy, AI can occasionally hallucinate or misinterpret complex legal nuances.</p>
      <div className="p-6 bg-red-500/5 border border-red-500/20 rounded-2xl text-red-400 text-sm">
        <strong>Important:</strong> Always consult with a qualified legal professional before signing any legally binding agreement. LegalAI is an intelligence tool, not a replacement for an attorney.
      </div>
    </section>
  </PageLayout>
);

export const Security = () => (
  <PageLayout title="Security" icon={Shield}>
    <section className="space-y-4">
      <h2 className="text-xl font-bold text-white">Enterprise-Grade Protection</h2>
      <p>Our infrastructure is built on secure cloud providers with 99.9% uptime and redundant security layers.</p>
      <ul className="list-disc pl-6 space-y-2">
        <li>AES-256 Encryption at rest</li>
        <li>TLS 1.3 Encryption in transit</li>
        <li>Automated vulnerability scanning</li>
        <li>SOC2 Type II Compliance (In Progress)</li>
      </ul>
    </section>
  </PageLayout>
);
